import { IngestionFailure } from '../../application/editorial-ingestion.mjs';
const timeoutFetch=async(fetchImpl,url,options={},timeoutMs=10000)=>{const c=new AbortController();const t=setTimeout(()=>c.abort(),timeoutMs);try{return await fetchImpl(url,{...options,signal:c.signal});}catch(e){throw new IngestionFailure(e?.name==='AbortError'?'SUBSOLO_INGEST_TIMEOUT':'SUBSOLO_INGEST_NETWORK_ERROR',e?.name==='AbortError'?'A fonte excedeu o tempo limite.':'Falha de rede na fonte de captação.','Verifique o serviço local e tente novamente.',{},true);}finally{clearTimeout(t);}};
const jsonResponse=async(response,service)=>{const text=await response.text();let data;try{data=text?JSON.parse(text):{};}catch{throw new IngestionFailure('SUBSOLO_INGEST_RESPONSE_INVALID',`${service} retornou JSON inválido.`,'Verifique a configuração do serviço.');}if(!response.ok)throw new IngestionFailure('SUBSOLO_INGEST_UPSTREAM_UNAVAILABLE',`${service} respondeu com HTTP ${response.status}.`,'Tente novamente e verifique o serviço.',{status:response.status},response.status===429||response.status>=500);return data;};
export const createFreshRssClient=({baseUrl,username,apiPassword,authToken,fetchImpl=globalThis.fetch,timeoutMs=10000})=>{
  const endpoint=String(baseUrl??'').replace(/\/$/,''); if(!endpoint)throw new IngestionFailure('SUBSOLO_INGEST_FRESHRSS_URL_MISSING','URL do FreshRSS ausente.','Configure SUBSOLO_FRESHRSS_API_URL.'); let token=authToken??null;
  const login=async()=>{if(token)return token;if(!username||!apiPassword)throw new IngestionFailure('SUBSOLO_INGEST_FRESHRSS_AUTH_MISSING','Credenciais de API do FreshRSS ausentes.','Configure usuário e senha de API em segredo local.');const response=await timeoutFetch(fetchImpl,`${endpoint}/accounts/ClientLogin`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({Email:username,Passwd:apiPassword}).toString()},timeoutMs);if(!response.ok)throw new IngestionFailure('SUBSOLO_INGEST_FRESHRSS_AUTH_INVALID','FreshRSS recusou a autenticação.','Revise o usuário e a senha específica da API.');const text=await response.text();token=text.match(/^Auth=(.+)$/m)?.[1]?.trim();if(!token)throw new IngestionFailure('SUBSOLO_INGEST_FRESHRSS_AUTH_INVALID','FreshRSS não retornou token de API.','Revise a configuração da API.');return token;};
  return{async listReadingList({limit=100,olderThanId=null}={}){const auth=await login();const url=new URL(`${endpoint}/reader/api/0/stream/contents/reading-list`);url.searchParams.set('output','json');url.searchParams.set('n',String(Math.min(500,Math.max(1,limit))));if(olderThanId)url.searchParams.set('c',olderThanId);const response=await timeoutFetch(fetchImpl,url,{headers:{Authorization:`GoogleLogin auth=${auth}`,accept:'application/json'}},timeoutMs);const data=await jsonResponse(response,'FreshRSS');return{entries:data.items??[],continuation:data.continuation??null};}};
};
export const createGmailIngestionClient=({accessToken,fetchImpl=globalThis.fetch,timeoutMs=10000})=>{
  if(!accessToken)throw new IngestionFailure('SUBSOLO_INGEST_GMAIL_AUTH_MISSING','Token somente leitura do Gmail ausente.','Configure um token com gmail.readonly fora do repositório.');const headers={authorization:`Bearer ${accessToken}`,accept:'application/json'};
  return{async listMessages({query='label:SUBSOLO/Pautas newer_than:2d',labelIds=[],maxResults=100}={}){const url=new URL('https://gmail.googleapis.com/gmail/v1/users/me/messages');url.searchParams.set('q',query);url.searchParams.set('maxResults',String(Math.min(500,maxResults)));for(const id of labelIds)url.searchParams.append('labelIds',id);const response=await timeoutFetch(fetchImpl,url,{headers},timeoutMs);return jsonResponse(response,'Gmail');},async getMessage(id){const response=await timeoutFetch(fetchImpl,`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(id)}?format=full`,{headers},timeoutMs);return jsonResponse(response,'Gmail');}};
};
export const createSearxngClient=({baseUrl='http://127.0.0.1:8081',fetchImpl=globalThis.fetch,timeoutMs=10000})=>({async search({query,categories='',language='pt-BR',pageno=1,timeRange=null}={}){if(!query?.trim())throw new IngestionFailure('SUBSOLO_INGEST_SEARXNG_QUERY_MISSING','Consulta SearXNG ausente.','Informe uma consulta editorial.');const url=new URL('/search',String(baseUrl).replace(/\/$/,'')+'/');url.searchParams.set('q',query);url.searchParams.set('format','json');url.searchParams.set('language',language);url.searchParams.set('pageno',String(pageno));if(categories)url.searchParams.set('categories',categories);if(timeRange)url.searchParams.set('time_range',timeRange);const response=await timeoutFetch(fetchImpl,url,{headers:{accept:'application/json'}},timeoutMs);const data=await jsonResponse(response,'SearXNG');return{entries:data.results??[],partial:Array.isArray(data.unresponsive_engines)&&data.unresponsive_engines.length>0,failedEngines:(data.unresponsive_engines??[]).map(x=>Array.isArray(x)?x[0]:String(x)),query};}});
