import test from 'node:test';import assert from 'node:assert/strict';import {readdir,readFile} from 'node:fs/promises';
const dir=new URL('../../n8n/workflows/',import.meta.url);
test('twelve sanitized workflows are valid and credential-free',async()=>{const files=(await readdir(dir)).filter(x=>x.endsWith('.json')).sort();assert.equal(files.length,12);for(const file of files){const raw=await readFile(new URL(file,dir),'utf8');const wf=JSON.parse(raw);assert.equal(wf.active,false);assert.equal(wf.meta.subsolo_export,'sanitized');assert.equal(/credential|access[_-]?token|private[_-]?key/i.test(raw),false,`${file} contains credential-like text`);assert.equal(/merge pull request|gh pr merge|auto.?merge/i.test(raw),false,`${file} attempts merge`);assert.equal(wf.nodes.some(n=>n.type==='n8n-nodes-base.code'),false,`${file} embeds domain code`);}});
test('Drive workflow precedes PR workflow in the exported map',async()=>{const drive=JSON.parse(await readFile(new URL('05_empacotamento_drive.json',dir),'utf8'));const names=drive.nodes.map(n=>n.name);assert.ok(names.indexOf('Preservar no Drive')<names.indexOf('Executar workflow 06'));});

test('ingestion workflows are triage-only and cannot publish',async()=>{for(const file of ['01_ingestao_freshrss.json','02_triagem_gmail.json','10_pesquisa_searxng.json']){const raw=await readFile(new URL(file,dir),'utf8');const wf=JSON.parse(raw);assert.equal(wf.meta.editorial_effect,'triage-only');assert.equal(/\b(?:publish|orchestrate|export-doc|package)\b/i.test(raw),false,`${file} has a publication command`);assert.match(raw,/\bingest\b/);}});
test('SearXNG workflow reads a fixed JSON query file instead of interpolating shell text',async()=>{const raw=await readFile(new URL('10_pesquisa_searxng.json',dir),'utf8');assert.match(raw,/--query-file \/workspace\/\.runtime\/input\/searxng-query\.json/);assert.equal(raw.includes('{{$json.query}}'),false);});

test('post-publication workflow preserves package before PR and requires human merge',async()=>{const raw=await readFile(new URL('11_pos_publicacao.json',dir),'utf8');const wf=JSON.parse(raw);const names=wf.nodes.map(n=>n.name);assert.ok(names.indexOf('Gerar e preservar pacote')<names.indexOf('Criar pull request'));assert.ok(names.indexOf('Criar pull request')<names.indexOf('Aguardar merge humano'));assert.match(raw,/post-publication/);});
